###############################################
### synth_generation_template.sh parameters ###
###############################################
#path to working directory
working_directory: /mnt/c/Users/sfragkoul/Desktop/synth_data/grid_datasets
#folder for results#######################11111
folder: 3000_50
#path to NEAT scripts
path_to_neat: /mnt/e/sfragkoul/Synth_Data/Synthesizers/NEAT
#number of individual synth batches 
runs: 10
#seeds for each individual synth batch#########################22222
rng: 466,470,473,475,477,478,480,481,482,483
#mutation rate parameter as taken from NEAT
mutation_rate: 0.1
#read length parameter as taken from NEAT#########################333333
read_length: 50
#coverage parameter as taken from NEAT####################444444
coverage: 300
#fragment parameters as taken from NEAT
fragment_stats: 
 1: 300
 2: 30
#path to reference file
path_to_reference: /mnt/e/sfragkoul/Synth_Data/Synthesizers/NEAT/testing/TP53/TP53.fasta
#name of final merged bam file
output_bam_merged: Merged

##############################################
### variant_calling_template.sh parameters ###
##############################################
#path to bam readcount scripts
path_to_bam_readcount: /home/sfragkoul
#somatic variant caller name
callers: Mutect2,Freebayes,LoFreq,VarScan,VarDict
#path to varscan_scripts_path extra scripts
varscan_scripts_path: /mnt/e/sfragkoul/Synth_Data/Synthesizers/NEAT/Varscan2VCF
#genomic region of interest as taken from VarScan
vardict_region_of_interest: hg38_knownGene_ENST00000610292.4:0-19080